name: '_COSMO Alpaca - Update System Files'

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to update
        required: true
        type: string
      templateUrl:
        description: Template Repository URL
        required: true
        type: string
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false

defaults:
  run:
    shell: pwsh

permissions:
  actions: read
  contents: read
  id-token: write

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  UpdateSystemFiles:
    name: "[${{ inputs.branch }}] Update COSMO Alpaca System Files"
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.branch }}

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v8.3
        with:
          shell: pwsh

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v8.3
        with:
          shell: pwsh
          get: commitOptions

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v8.3
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Calculate Commit Options
        env:
          directCommit: '${{ inputs.directCommit }}'
          downloadLatest: '${{ inputs.downloadLatest }}'
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          if('${{ github.event_name }}' -in 'workflow_dispatch', 'workflow_call') {
            Write-Host "Using inputs from ${{ github.event_name }} event"
            $directCommit = $env:directCommit
            $downloadLatest = $env:downloadLatest
          }
          else {
            Write-Host "Using inputs from commitOptions setting"
            $commitOptions = $env:commitOptions | ConvertFrom-Json # Available from ReadSettings step
            $directCommit=$(-not $commitOptions.createPullRequest)
            $downloadLatest=$true
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Update COSMO Alpaca system files
        uses: cosmoconsult/Alpaca-Actions/Actions/UpdateSystemFiles@v2.7
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          updateBranch: ${{ inputs.branch }}
          templateUrl: ${{ inputs.templateUrl }}
          downloadLatest: ${{ env.downloadLatest }}
          directCommit: ${{ env.directCommit }}
