name: '_COSMO Alpaca - Remove Containers'

on:
  workflow_call:
    inputs:
      backendUrl:
        description: COSMO Alpaca backend Url
        required: true
        type: string
      projectFilter:
        description: Optional filter for project name
        required: false
        type: string
        default: '*'
      buildModeFilter:
        description: Optional filter for build mode
        required: false
        type: string
        default: '*'

defaults:
  run:
    shell: pwsh

env:
  ALPACA_BACKEND_URL: ${{ inputs.backendUrl }}

jobs:
  RemoveAlpacaContainers:
    name: Remove COSMO Alpaca Containers
    runs-on: [ ubuntu-latest ]
    steps:
      - id: RemoveContainers
        name: Remove Containers
        uses: cosmoconsult/Alpaca-Actions/Actions/RemoveContainers@v2.10
        with:
          shell: pwsh
          token: ${{ secrets.GITHUB_TOKEN }}
          projectFilter: ${{ inputs.projectFilter }}
          buildModeFilter: ${{ inputs.buildModeFilter }}
